<<<<<<< HEAD
# Generated by Django 4.2.30 on 2026-09-18 10:56
=======
# Generated by Django 6.0.7 on 2026-07-30 10:55
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
=======
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
