<<<<<<< HEAD
<<<<<<< HEAD
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#9)0$$4yw3j41g1tdyr4q&g2970((a*q@z6ui$k#e+iv+o&vl$'

# SECURITY WARNING: don't run with debug turned on in production!
=======
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-replace-this-key-for-production'

<<<<<<< HEAD
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
<<<<<<< HEAD

# Application definition

=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<< HEAD
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters', 
=======
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
    
    # Custom and Third-Party Apps
    'rest_framework',
    'django_filters',  # Added for DRF search, filter, and ordering backends
<<<<<<< HEAD
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

<<<<<<< HEAD
<<<<<<< HEAD

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD
<<<<<<< HEAD

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD
<<<<<<< HEAD

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

<<<<<<< HEAD
<<<<<<< HEAD

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5, 
    'DEFAULT_PARSER_CLASSES': [ 
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser', 
        'rest_framework.parsers.MultiPartParser', 
    ], 
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=36), # Change this to your desired duration (e.g., 1 day, 2 hours, etc.)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # How long refresh tokens last
}
=======
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}
<<<<<<< HEAD
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
=======
>>>>>>> fc9e15cac64e90c9743f8920246eede0efd88882
